# Learn more about this file at https://www.gitpod.io/docs/references/gitpod-yml
checkoutLocation: webstone
workspaceLocation: .

tasks:
  - before: |
      npm install -g pnpm
      cd webstone
    init: |
      pnpm install
      gp sync-done install
    command: pnpm dev
  - before: npm install -g pnpm
    init: |
      gp sync-await install
      node ./webstone/packages/create-webstone-app/bin webstone-dev-app
    command: |
      cd webstone-dev-app
      pnpm link ../webstone/packages/cli
      pnpm dev
    openMode: split-right

ports:
  - port: 3000
    visibility: public