---
# Learn more about this file at https://www.gitpod.io/docs/references/gitpod-yml
image:
  file: .gitpod/Dockerfile

checkoutLocation: webstone
workspaceLocation: .

tasks:
  - name: Webstone Dev
    before: |
      npm install -g pnpm
      gp sync-done pnpm-installed-globally
      cd webstone
      pnpm install
      pnpx cypress install
      gp sync-done dependencies-installed
    command: |
      pnpm dev
  - name: App Dev
    before: |
      gp sync-await pnpm-installed-globally
    init: |
      gp sync-await dependencies-installed
      node ./webstone/packages/create-webstone-app/bin webstone-dev-app
    command: |
      cd webstone-dev-app
      while [ ! -f ../webstone/packages/cli/dist/bin.js ]; do sleep 1; done
      pnpm add -w -D ../webstone/packages/cli
      export HMR_HOST=`gp url 3000`
      pnpm ws dev gitpod web-patch-svelte-config-js
      pnpm ws dev
    openMode: split-right
  - name: App Tests
    before: |
      gp sync-await pnpm-installed-globally
    command: |
      cd webstone
      gp await-port 3000
      pnpm test:e2e

ports:
  - port: 3000
    visibility: public
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: ignore

vscode:
  extensions:
    - svelte.svelte-vscode
    - yzhang.markdown-all-in-one
    - dbaeumer.vscode-eslint
