---
# Learn more about this file at https://www.gitpod.io/docs/references/gitpod-yml
image: gitpod/workspace-full-vnc

checkoutLocation: webstone
workspaceLocation: .

tasks:
  - name: Webstone Dev
    before: ./webstone/.gitpod/tasks/1-webstone-dev/before.sh
    command: ./webstone/.gitpod/tasks/1-webstone-dev/command.sh
  - name: App Dev
    before: ./webstone/.gitpod/tasks/2-app-dev/before.sh
    init: ./webstone/.gitpod/tasks/2-app-dev/init.sh
    command: ./webstone/.gitpod/tasks/2-app-dev/command.sh
    openMode: split-right
  - name: App Tests
    before: ./webstone/.gitpod/tasks/3-app-tests/before.sh
    command: |
      ./webstone/.gitpod/tasks/3-app-tests/command.sh
      cd webstone
  - name: App Dev (misc)
    command: cd webstone-dev-app

ports:
  - port: 5173
    visibility: public
    onOpen: ignore
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: ignore

vscode:
  extensions:
    - svelte.svelte-vscode
    - yzhang.markdown-all-in-one
    - dbaeumer.vscode-eslint
    - ms-playwright.playwright
