# Learn more about this file at https://www.gitpod.io/docs/references/gitpod-yml
image:
  file: .gitpod/Dockerfile

checkoutLocation: webstone
workspaceLocation: .

tasks:
  - before: |
      npm install -g pnpm
      cd webstone
    init: |
      pnpm install
      pnpx cypress install
      gp sync-done install
    command: pnpm dev
  - before: npm install -g pnpm
    init: |
      gp sync-await install
      cd webstone/tests/e2e
      pnpx cypress run --spec "cypress/integration/1-getting-started/**/**"
    command: |
      echo "TODO: Re-enable the commented lines below in .gitpod.yml"
    # command: |
    #   cd /workspace/webstone-dev-app
    #   while [ ! -f ../webstone/packages/cli/dist/bin.js ]; do sleep 1; done
    #   pnpm add -w -D ../webstone/packages/cli
    #   export HMR_HOST=`gp url 3000`
    #   pnpm ws dev gitpod web-patch-svelte-config-js
    #   pnpm ws dev
    openMode: split-right

ports:
  - port: 3000
    visibility: public
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: ignore

vscode:
  extensions:
    - svelte.svelte-vscode
    - yzhang.markdown-all-in-one